name: local_database
description: "The local database implemented in the provided Dart code is a simplified key-value store designed for local data storage. It consists of three main classes: LocalDatabase, LCR (Local Collection Reference), and LDR (Local Document Reference)"
version: 1.0.0
repository: https://github.com/Mohiuddin655-YMR/flutter_local_database.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
